"""Plain-text and HTML report generators (no external deps)."""
from typing import List
from openffs.core.result import AssessmentResult
from openffs.standards.notifier import check_currency, format_notifications


SEPARATOR = "=" * 72; SUBSEP = "-" * 72


def render_text_report(results, project_name="OpenFFS Assessment", standard_edition="API 579-1/ASME FFS-1 2021"):
    out = [SEPARATOR, f"  {project_name}", "  Generated by OpenFFS v0.7.0",
           f"  Standard: {standard_edition}", SEPARATOR, ""]
    notifs = check_currency()
    if notifs: out += ["STANDARDS CURRENCY:", format_notifications(notifs), ""]
    out += [SUBSEP, "EXECUTIVE SUMMARY", SUBSEP]
    n_total = len(results)
    n_suitable = sum(1 for r in results if r.is_suitable and not r.requires_escalation)
    n_escalate = sum(1 for r in results if r.requires_escalation)
    n_replace = sum(1 for r in results if r.suitability == "Replace")
    out += [f"Components assessed: {n_total}",
            f"  Suitable (continue / repair):  {n_suitable}",
            f"  Escalate to L2/L3:             {n_escalate}",
            f"  Replace:                       {n_replace}", ""]
    out += [SUBSEP, "PER-COMPONENT ASSESSMENTS", SUBSEP]
    for r in results:
        out += ["", f"Component: {r.component_id}", f"  Track:     {r.track}",
                f"  Level:     {r.level}", f"  Verdict:   {r.suitability}",
                f"  Governing: {r.governing_clause}"]
        if r.rsf is not None: out.append(f"  RSF:       {r.rsf:.4f}")
        if r.mawp is not None: out.append(f"  MAWP:      {r.mawp:.4f} MPa")
        if r.dc_ratio is not None: out.append(f"  DC ratio:  {r.dc_ratio:.4f}")
        if r.remaining_life is not None: out.append(f"  Remaining life: {r.remaining_life:.2f} yr")
        if r.warnings: out.append("  Warnings:"); [out.append(f"    - {w}") for w in r.warnings]
        out.append("  Calculation log:")
        for step in r.calculation_log: out.append(f"    {step}")
    out += ["", SEPARATOR, "  END OF REPORT", SEPARATOR]
    return "\n".join(out)


def render_html_report(results, project_name="OpenFFS Assessment", standard_edition="API 579-1/ASME FFS-1 2021"):
    n_total = len(results); n_suitable = sum(1 for r in results if r.is_suitable and not r.requires_escalation)
    n_escalate = sum(1 for r in results if r.requires_escalation)
    n_replace = sum(1 for r in results if r.suitability == "Replace")
    parts = ['<!DOCTYPE html><html><head><meta charset="utf-8"><title>OpenFFS Report</title>',
             '<style>body{font-family:Segoe UI,Tahoma,sans-serif;margin:24px}h1{color:#1a4d8f;border-bottom:2px solid #1a4d8f;padding-bottom:8px}h2{color:#1a4d8f;margin-top:32px}.summary{background:#f4f7fb;padding:16px;border-left:4px solid #1a4d8f;margin:16px 0}.component{border:1px solid #ccc;margin:16px 0;padding:16px;border-radius:4px}.verdict{font-size:1.2em;font-weight:bold;padding:4px 12px;display:inline-block;border-radius:4px;color:white}.suitable{background:#2d8a4e}.repair{background:#d99a00}.replace{background:#c43030}.escalate{background:#6a4dc4}.log{background:#f8f8f8;padding:8px;font-family:Consolas,monospace;font-size:0.85em}table{border-collapse:collapse;width:100%;margin:8px 0}th,td{border:1px solid #ddd;padding:8px;text-align:left}th{background:#1a4d8f;color:white}.warning{color:#c43030;font-style:italic}</style></head><body>']
    parts.append(f"<h1>{project_name}</h1>")
    parts.append(f"<p><strong>Generated by:</strong> OpenFFS v0.7.0 &nbsp;|&nbsp; <strong>Standard:</strong> {standard_edition}</p>")
    parts.append("<div class='summary'><h2>Executive Summary</h2>")
    parts.append(f"<table><tr><th>Components assessed</th><td>{n_total}</td></tr><tr><th>Suitable (continue/repair)</th><td>{n_suitable}</td></tr><tr><th>Escalate to L2/L3</th><td>{n_escalate}</td></tr><tr><th>Replace</th><td>{n_replace}</td></tr></table></div>")
    parts.append("<h2>Per-Component Assessments</h2>")
    for r in results:
        if r.is_suitable and not r.requires_escalation: cls = "suitable"
        elif r.suitability == "Replace": cls = "replace"
        elif r.requires_escalation: cls = "escalate"
        else: cls = "repair"
        parts.append("<div class='component'>")
        parts.append(f"<h3>{r.component_id}</h3>")
        parts.append(f"<p><span class='verdict {cls}'>{r.suitability}</span></p>")
        parts.append(f"<p><strong>Track:</strong> {r.track} &nbsp;|&nbsp; <strong>Level:</strong> {r.level}<br><strong>Governing clause:</strong> {r.governing_clause}</p>")
        if any(x is not None for x in [r.rsf, r.mawp, r.dc_ratio, r.remaining_life]):
            parts.append("<table><tr><th>Metric</th><th>Value</th></tr>")
            if r.rsf is not None: parts.append(f"<tr><td>RSF</td><td>{r.rsf:.4f}</td></tr>")
            if r.mawp is not None: parts.append(f"<tr><td>MAWP</td><td>{r.mawp:.4f} MPa</td></tr>")
            if r.dc_ratio is not None: parts.append(f"<tr><td>DC ratio</td><td>{r.dc_ratio:.4f}</td></tr>")
            if r.remaining_life is not None: parts.append(f"<tr><td>Remaining life</td><td>{r.remaining_life:.2f} yr</td></tr>")
            parts.append("</table>")
        if r.warnings:
            parts.append("<p class='warning'><strong>Warnings:</strong><br>")
            for w in r.warnings: parts.append(f"&nbsp;- {w}<br>")
            parts.append("</p>")
        if r.calculation_log:
            parts.append("<details><summary>Calculation audit log</summary><div class='log'>")
            for step in r.calculation_log: parts.append(f"&nbsp;{step}<br>")
            parts.append("</div></details>")
        parts.append("</div>")
    parts.append("</body></html>")
    return "\n".join(parts)


def render_pdf_report(results, output_path, project_name="OpenFFS Assessment", standard_edition="API 579-1/ASME FFS-1 2021"):
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib import colors
    except ImportError: return False
    doc = SimpleDocTemplate(output_path, pagesize=letter, leftMargin=36, rightMargin=36, topMargin=36, bottomMargin=36)
    styles = getSampleStyleSheet(); h1 = styles["Heading1"]; h2 = styles["Heading2"]; body = styles["Normal"]
    small = ParagraphStyle("small", parent=body, fontSize=8, leading=10)
    elements = [Paragraph(project_name, h1), Paragraph(f"<b>OpenFFS v0.7.0</b> &nbsp;&nbsp; Standard: {standard_edition}", small), Spacer(1, 12)]
    elements.append(Paragraph("Executive Summary", h2))
    n_total = len(results); n_suitable = sum(1 for r in results if r.is_suitable and not r.requires_escalation)
    n_escalate = sum(1 for r in results if r.requires_escalation); n_replace = sum(1 for r in results if r.suitability == "Replace")
    t = Table([["Metric", "Value"], ["Components assessed", str(n_total)], ["Suitable", str(n_suitable)],
               ["Escalate", str(n_escalate)], ["Replace", str(n_replace)]], colWidths=[250, 100])
    t.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a4d8f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey), ("FONTSIZE", (0, 0), (-1, -1), 9)]))
    elements.append(t); elements.append(Spacer(1, 16))
    elements.append(Paragraph("Per-Component Assessments", h2))
    for r in results:
        elements.append(Paragraph(f"<b>{r.component_id}</b>", body))
        elements.append(Paragraph(f"<b>Verdict:</b> {r.suitability}", body))
        elements.append(Paragraph(f"<b>Track / Level:</b> {r.track} / L{r.level}", small))
        elements.append(Paragraph(f"<b>Governing:</b> {r.governing_clause}", small))
        elements.append(Spacer(1, 12))
    doc.build(elements)
    return True
